#!/bin/sh
# Copyright (C) 2019 GL.iNet
#
# This is free software, licensed under the GNU General Public License v3.
# See /LICENSE for more information.
#
SERVICE_DEV=""
SERVICE_IF=""

init_var()
{
	local ifname
	config_get ifname  global ifname
	SERVICE_IF=${ifname}
}

config_load portal-detect
config_foreach init_var

[ "$SERVICE_IF" = "" ] && exit 0

[ "$ACTION" = "remove" -a "$DEVICENAME" = "$SERVICE_IF" ] && {
	for i in $(fuser /usr/bin/portal-detect);do
		kill $i
	done
}
