#!/bin/sh
# Copyright (C) 2019 GL.iNet
#
# This is free software, licensed under the GNU General Public License v2.
# See /LICENSE for more information.
#

[ "$ACTION" = "remove" -a "$DEVICENAME" = "wlan-sta" ] && {
	logger "portal-detect wlan-sta remove"
	for i in $(fuser /usr/bin/portal-detect);do
		logger "kill portal-detect $i"
		kill $i
	done
}
